# Generated by Django 5.2.6 on 2025-12-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_logindevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="logindevice",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="logindevice",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
