# Generated by Django 5.2.6 on 2025-12-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobSeekerProfile", "0006_merge_20251023_0952"),
        ("Jobs", "0012_remove_jobcategory_unique_category_per_employer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="applied_categories",
            field=models.ManyToManyField(blank=True, to="Jobs.jobcategory"),
        ),
    ]
