# Generated by Django 5.2.6 on 2025-12-26 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("JobSeekerProfile", "0007_jobseekerprofile_applied_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="applied_categories",
        ),
    ]
