# Generated by Django 5.2.6 on 2025-12-30 02:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("EmployerProfile", "0003_employeremailverification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="Jobs.jobcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("MO", "MRAUK-U"),
                            ("MB", "MINBRAR"),
                            ("SIT", "SITTWE"),
                            ("RD", "RETHEEDAUNG"),
                            ("MD", "MAUNGDAW"),
                            ("KP", "KYAWTPYHU"),
                            ("TD", "THANDWE"),
                            ("TG", "TOUNGUP"),
                            ("AN", "ANN"),
                            ("PNG", "PONNAGYUN"),
                            ("KT", "KYAUKTAW"),
                            ("RM", "RAMREE"),
                            ("MA", "MANAUNG"),
                            ("GW", "GWA"),
                            ("PT", "PAUKTAW"),
                            ("BTD", "BUTHIDAUNG"),
                            ("MB", "MYEBON"),
                        ],
                        default="MO",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full-time"),
                            ("PART", "Part-time"),
                            ("INTERN", "Internship"),
                            ("REMOTE", "Remote"),
                        ],
                        default="FULL",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_applicants",
                    models.PositiveIntegerField(
                        default=0, help_text="Maximum number of allowed applicants"
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NORMAL", "Normal"),
                            ("FEATURED", "Featured"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        help_text="Use FEATURED for top placement or URGENT for visible badge.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Jobs.jobcategory",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="EmployerProfile.employerprofile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="jobcategory",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_category_per_user"
            ),
        ),
    ]
