# Generated by Django 5.2.6 on 2025-12-26 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0012_remove_jobcategory_unique_category_per_employer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="Jobs.jobcategory",
            ),
        ),
    ]
