# Generated by Django 5.2.6 on 2025-12-30 02:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("JobSeekerProfile", "__first__"),
        ("Jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("P", "Pending"),
                            ("H", "Hired"),
                            ("RJ", "Rejected"),
                            ("R", "Review"),
                            ("SL", "ShortList"),
                        ],
                        default="P",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("cover_letter_text", models.TextField(null=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="Jobs.jobs",
                    ),
                ),
                (
                    "job_seeker_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="JobSeekerProfile.jobseekerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaveJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Jobs.jobs",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to="JobSeekerProfile.jobseekerprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "job"),
                        name="unique_save_job_per_jobseeker_job",
                    )
                ],
            },
        ),
    ]
