# Generated by Django 5.2.6 on 2025-12-17 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0004_alter_application_job"),
        ("Jobs", "0012_remove_jobcategory_unique_category_per_employer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="Jobs.jobs",
            ),
        ),
    ]
