# Generated by Django 5.2.6 on 2025-12-26 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0005_alter_application_job"),
        ("JobSeekerProfile", "0008_remove_jobseekerprofile_applied_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="job_seeker_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="JobSeekerProfile.jobseekerprofile",
            ),
        ),
    ]
